### PR TITLE
Fix binary mode search #365

### LINKED ISSUE #365: Bytes searching get wrong result
I try to find pattern "de" in binary file, but result is "fe" or "de".
screenshot-20220705-164807

### PR DESCRIPTION
**Pull request by varblane**
Fixes #365. The search function was trying to apply case insensitivity rules to bytes, equating e.g. `41` with `61`. Made it ignore case sensitivity settings in binary mode.

### CODE REVIEW

File: media/editor/findWidget.tsx [hunk 1]
```diff
@@ -234,6 +234,7 @@ export const FindWidget: React.FC = () => {
 				cap: isUncapped ? undefined : defaultResultCap,
 				query: queryOrError,
 				caseSensitive: isCaseSensitive,
+				binaryMode: isBinaryMode,
```
Comment (connor4312) [inline media/editor/findWidget.tsx:237]: Thanks for the PR! This could just be

```suggestion
				caseSensitive: isBinaryMode || isCaseSensitive,
```

...and the other files would not need to change

Comment (varblane) [reply media/editor/findWidget.tsx]: Oh, yeah. You're right. I didn't reailize I could just do that.

**Review by connor4312 — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]

**Comment by connor4312** [comment]
Thanks again for the PR!
